config/routes.rb
ImaginalUpgrade::Application.routes.draw do

  ActiveAdmin.routes(self)

  match 'users/sign_in' => 'pages#home', via: 'get'

  devise_for :users, :skip => [:registrations, :passwords], :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root :to => "pages#home"

  get 'profiles/:id/:name', :to => 'profiles#show'
  resources :profiles, only: [:show]

  get 'videos/:id/:name', :to => 'videos#show'
  put 'videos/:id/:name', :to => 'videos#update'
  post 'videos/:id', :to => 'videos#destroy'
  post 'videos/:id/:name', :to => 'videos#destroy'
  resources :videos

  resources :categories
  resources :tags

  match '/add_rating' => 'ratings#add_rating', via: 'post'

  match '/set_preference' => 'preferences#set_preference', via: 'post'

  get '/:id', to: 'pages#show'

end

app/models/video.rb
class Video < ActiveRecord::Base
  
  belongs_to :user
  has_many :ratings, :dependent => :destroy
  has_many :averages, :dependent => :destroy

  before_create :get_video_attributes

  #before_save :parse_video_url, :get_video_thumbnail_link
  validates :title, :description, :url, :presence => true
  validates :url, :title, uniqueness: true
  validates_length_of :description, :maximum => 250

  acts_as_taggable # Alias for acts_as_taggable_on :tags

  def self.search(query)
    where("lower(title) like ? OR lower(description) like ?", "%#{query.downcase}%", "%#{query.downcase}%")
  end

  def get_average_rating_for_category(id)
    average = Average.find_by_category_id_and_video_id(id, self.id)
    average == nil ? 0 : average.average
  end

  def average_rating
    average_rating = self.overall_rating.round
  end

  def update_overall_video_rating(rating)
    self.overall_stars += rating.num_stars 
    self.overall_votes += 1 
    self.overall_rating = self.overall_stars/self.overall_votes
    self.save
  end

  def get_video_type(url)
    if (/vimeo.com/).match(url)
      get_video_type = 'vimeo'
     elsif (/youtube.com/).match(url)
       get_video_type = 'youtube'
    end
  end

  def get_video_id(url)
    if (/vimeo.com/).match(url)
      get_video_id = (/(\d+)($|\/)/.match(self.url)).to_s
    elsif (/youtube.com/).match(url)
      get_video_id = (/([\w-]{11})/.match(self.url)).to_s
    end
  end

  def embed_code
    if self.provider == 'vimeo'
      embed_code = "<iframe src='http://player.vimeo.com/video/#{self.provider_id}?title=0&byline=0&portrait=0' width='900' height='500' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>"
    elsif self.provider == 'youtube'
      embed_code = "<iframe width='900' height='500' src='//www.youtube.com/embed/#{self.provider_id}?modestbranding=1&showinfo=0&rel=0&hd=1&controls=1&wmode=opaque' frameborder='0' allowfullscreen></iframe>"
    end
  end

  def thumbnail_old
    if self.provider == 'vimeo'
      thumbnail = "https://images1-focus-opensocial.googleusercontent.com/gadgets/proxy?url=https%3A%2F%2Fres.cloudinary.com%2Fdemo%2Fimage%2Fvimeo%2F#{self.provider_id}.jpg&container=focus&resize_w=210&resize_h=140&refresh=2592000"
    elsif self.provider == 'youtube'
      thumbnail = "https://images1-focus-opensocial.googleusercontent.com/gadgets/proxy?url=https%3A%2F%2Fimg.youtube.com%2Fvi%2F#{self.provider_id}%2F0.jpg&container=focus&resize_w=210&resize_h=140&refresh=2592000"
    end
  end

  def thumbnail
    if self.provider == 'vimeo'
      thumbnail = "https://images1-focus-opensocial.googleusercontent.com/gadgets/proxy?url=https%3A%2F%2Fres.cloudinary.com%2Fdemo%2Fimage%2Fvimeo%2F#{self.provider_id}.jpg&container=focus&resize_h=220&rsize_w=220&refresh=2592000"
    elsif self.provider == 'youtube'
      thumbnail = "https://images1-focus-opensocial.googleusercontent.com/gadgets/proxy?url=https%3A%2F%2Fimg.youtube.com%2Fvi%2F#{self.provider_id}%2F0.jpg&container=focus&resize_h=220&resize_w=220&refresh=2592000"
    end
  end

  def facebook_thumbnail
    if self.provider == 'youtube'
      facebook_thumbnail = "http://i1.ytimg.com/vi/#{self.provider_id}/hqdefault.jpg?feature=og"
    else
      facebook_thumbnail = ''
    end

  end

  private

  def get_video_attributes

    require 'open-uri'
    require 'json'

      provider = self.get_video_type(self.url)
      provider_id = self.get_video_id(self.url)

      if provider == 'vimeo'
        result = JSON.parse(open("http://vimeo.com/api/oembed.json?url=http%3A//vimeo.com/#{provider_id}").read)
      elsif provider == 'youtube'
        result = JSON.parse(open("http://www.youtube.com/oembed?url=http%3A//www.youtube.com/watch?v%3D#{provider_id}&format=json").read)
      end

      self.provider = provider
      self.provider_id = provider_id
      self.video_width = result['width']
      self.video_height = result['height']
      self.thumbnail_width = result['thumbnail_width']
      self.thumbnail_height = result['thumbnail_height']

  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  before_filter :authenticate_user!, except: [:index, :show, :create]
  before_filter :update_click_count, only: [:show]
  before_filter :find_video, only: [:edit, :update, :destroy]
  
  def index
    if params[:search]
      @page_title = "Search - " + params[:search]
      @videos = Video.search(params[:search]).where(temporary_owner: '').order('overall_rating DESC').page params[:page]
    else
      @page_title = "All Videos"
      @videos  = Video.where(temporary_owner: '').order('overall_rating DESC').page params[:page]
    end

    @video = Video.new
  end

  def show

    @show_video = Video.find_by(temporary_owner: '', id: params[:id])

    if @show_video

      @page_title = @show_video.title

      @show_video.update_attribute(:plays, @show_video.plays + 1)
      #@show_video_user = User.find(@show_video.user_id)
      @videos = Video.all

      @small_vids = @videos.sample(20)
      @categories = Category.all.order('sort_order ASC')
      @rating = Rating.new
      @video = Video.new


      @category_averages = []

      @categories.each do |category|
        @category_averages[category.id] = @show_video.get_average_rating_for_category(category.id)
      end

    else
      redirect_to videos_path
    end
  end

  def new
    redirect_to videos_path
  end

  def create

    @video = Video.create(video_params)

    if current_user
     @video.user = current_user
    else
     random_string = (0...50).map { ('a'..'z').to_a[rand(26)] }.join
     @video.temporary_owner = random_string
     cookies[:publish_video] = random_string
    end

    if @video.save
      flash[:new] = 'true'

      if current_user
        redirect_to video_path(@video)
      else
        redirect_to user_omniauth_authorize_path(:facebook)
      end

    else
      flash[:alert] = "Due to the following your video has not been saved: #{@video.errors.full_messages.join(", ")}. Please try again."
      redirect_to root_path
    end
  end

  def edit
    redirect_to videos_path
  end

  def update
    if @video.update_attributes(video_params)
      redirect_to "/videos/#{@video.id}/#{@video.title.parameterize}" #not sure why video_path doesn't use the helper method we overloaded
    else
      render :edit
    end
  end

  def destroy
    @video.destroy
    flash[:notice] = "Video deleted."
    redirect_to root_path
  end

  private

  def video_params
    params.require(:video).permit(:link, :title, :url, :description, :feature, :tag_list, :post_to_facebook)
  end

  def update_click_count
    @show_video = Video.find(params[:id])
    @show_video.click_count += 1
    @show_video.save
  end

  def find_video
    @video = Video.find(params[:id])
  end

end

app/views/videos/_form.html.erb
<!-- Modal -->
<div class="modal fade submit-vid-form" id="submit-vid-form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h1>SUBMIT A VIDEO</h1>
            </div>
            <div class="modal-body">
                <%= form_for @video do |f| %>
                    <h2>TITLE</h2>
                    <h5>Give the video a snazzy title that makes people curious, e.g. "How to Start a Movement in 3 Minutes"</h5>
                    <%= f.text_field :title, :size => "80x40", required: :true, :autofocus => true, remote: true %>
                    <h2>URL</h2><h5>(Vimeo or YouTube)</h5>
                    <%= f.text_field :url, :size => "80x40", placeholder: 'http://', required: :true %>
                    <h2>DESCRIPTION</h2>
                    <h5>Tell us how this video impacted you and why it matters.</h5>
                    <%= f.text_area :description, :size => "81x4", :rows => 3, required: :true %><br>
                    <div class="modal-footer">
                        <% if current_user %>
                            <%= f.submit "Done" %>
                        <% else %>
                            <%= f.submit "Sign in with Facebook" %>
                        <% end %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

<% if current_user %>

    <% if @show_video && (flash[:new] || params[:new]) && (@show_video.user_id == current_user.id || current_user.is_admin?) %>

        <script type="text/javascript">
            $(document).ready(function(){
                $('#tag-vid-form').modal('show');
            });
        </script>

        <!-- Modal -->
        <div class="modal fade submit-vid-form" id="tag-vid-form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h1>YOUR VIDEO HAS BEEN CREATED</h1>
                        <p>Please take a moment to add some tags to the video.</p>
                    </div>
                    <div class="modal-body">
                        <%= form_for :video, method: :put do |f| %>
                            <%= f.hidden_field :feature, :value => @show_video.feature %>
                            <h2>TAGS</h2>
                            <h5>Tags separated by commas.</h5>
                            <%= f.text_field :tag_list, :value => @show_video.tag_list %>
                            <div class="modal-footer">
                                <%= f.submit "Add Tags" %>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>

    <% if @show_video && (@show_video.user_id == current_user.id || current_user.is_admin?) %>

        <!-- Modal -->
        <div class="modal fade submit-vid-form" id="delete-vid-form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h1>DELETE VIDEO</h1>
                    </div>
                    <div class="modal-body">
                        <%= form_for :video, method: :destroy do |f| %>
                            <h5>Are you sure you want to delete this video?</h5>
                            <div class="modal-footer">
                                <%= f.submit "Delete This Video" %>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>

        <!-- Modal -->
        <div class="modal fade submit-vid-form" id="edit-vid-form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h1>EDIT VIDEO</h1>
                    </div>
                    <div class="modal-body">
                        <%= form_for :video, method: :put do |f| %>
                            <%= f.hidden_field :feature, :value => @show_video.feature %>
                            <h2>TITLE</h2>
                            <h5>Give the video a snazzy title that makes people curious, e.g. "How to Start a Movement in 3 Minutes"</h5>
                            <%= f.text_field :title, :size => "80x40", required: :true, :autofocus => true, remote: true, :value => @show_video.title %>
                            <h2>URL</h2><h5>(Vimeo or YouTube)</h5>
                            <%= f.text_field :url, :size => "80x40", placeholder: 'http://', required: :true, :value => @show_video.url %>
                            <h2>DESCRIPTION</h2>
                            <h5>Tell us how this video impacted you and why it matters.</h5>
                            <%= f.text_area :description, :size => "81x4", :rows => 3, required: :true, :value => @show_video.description %><br>
                            <h2>TAGS</h2>
                            <h5>Tags separated by commas.</h5>
                            <%= f.text_field :tag_list, :value => @show_video.tag_list %>
                            <div class="modal-footer">
                                <%= f.submit "Done" %>
                            </div>
                            <div>
                                <a href="#" class="delete-video">Delete This Video</a>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
<% end %>

app/views/videos/index.html.erb
<div class="container">

  <h2>Looking for any film in particular?</h2>

  <%= form_tag(videos_path, :method => 'get', class: "navbar-form", id: "search-form") do %>

  <div class="search">
    <div class="input-group">
      <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search Videos" %>
      <span class="input-group-btn">
        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
      </span>
    </div>
  </div>
  <% end %>

  <%= render 'shared/videos' %>

</div>

app/views/videos/show.html.erb
<div class="container">
  <div class="main-video">
    <h1><%= @show_video.title %>
      <% if current_user && (@show_video.user_id == current_user.id || current_user.is_admin?)  %>
        <a href="#" class="edit-video">Edit Video</a>
      <% end %></h1>

    <div class="vid-link">

        <script type="text/javascript">
          function playerFinished() {

            $('.finished-popup .watch-again').click(function() {
               $(this).parent().parent().hide();
               $('#player').show();
                playerStart();
            });

            $('.finished-popup').width($('#player').width()).css('min-height', $('#player').height());
            $('#player').hide();
            $('.finished-popup').show();

          }
          $(window).resize(function() {
            $('.finished-popup').width($('#player').width()).css('min-height', $('#player').height());
          });

        </script>

        <% if flash[:new] || params[:new] %>
            <% autoplay = false %>
        <% else %>
            <% autoplay = false %>
        <% end %>

        <%= render "shared/player", video: @show_video, autoplay: autoplay %>

        <div class="finished-popup">
            <form method="post" action="#">
                <h3>We'd love you to join our community!</h3>
                <p><input type="text" name="full-name" placeholder="Full name" value=""></p>
                <p><input type="text" name="email" placeholder="E-mail Address" value=""></p>
                <p><button>Register</button></p>
            </form>
            <div class="buttons">
                <button class="watch-again">Watch Video Again</button>
            </div>
        </div>


    </div>

    <div class="add-stars-box">

      <% if flash[:alert] %>
      <p class="notice"><%= notice %></p>
      <% end %>
      
      <div id="star-brand"><h2>Vote. Share. Change the World.</h2></div>
        <% @categories.each_with_index do |category, index| %>
          <div class="cat" id="category-<%=category.id %>" >
            <div tooltip="<%= category.description %>" class="tooltip<%=index+1 %>">
              <h5 data-default="<%=category.name %>" data-alternates="<%=category.name %><% if category.alternates != '' %>, <%=category.alternates %><% end %>">
                <%= user_preference('category-' + category.id.to_s, category.name) %></h5>
            </div>
            <div class="stars stars<%=index+1 %>" data-avg="<%= @category_averages[category.id] %>" >
              <div class="starbox">
                <div class="colorBoxAverage"></div>
                <div class="colorBoxInteraction"></div>
                <ul>
                    <% 1.upto(5) do |i| %>
                      <li class="star"><%= link_to image_tag("../assets/bigger-star-from-Jeff.png"), add_rating_path(@rating, num_stars: i, video_id: @show_video.id, category_id: category.id), data: {:name => user_preference('category-' + category.id.to_s, category.name), :rating => i, :rated => Rating.previous_rating_found?(@show_video.id, category.id, request.remote_ip) } %></li>
                    <% end %>
                </ul>
              </div>
          </div>
        </div>
      <% end %>
     </div>

     <div class="full-share" id="fb-image"><%=link_to image_tag('../assets/Facebook_share_button.png') %></div>
     <div class="description">
         <p><a href="<%=profile_path(@show_video.user.profile) %>"><% if @show_video.user.uid != '' %>
               <img alt="" title="" src="https://graph.facebook.com/<%= @show_video.user.uid %>/picture?type=square" />
               <% end %>
             <%=@show_video.user.name %></a></p>
         <p><%= @show_video.description %></p>
         <% if @show_video.tag_list.count != 0 %>
         <div class="tags">
             Tags: <%= raw @show_video.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
         </div>
         <% end %>
     </div>


    <div class="share">
      
     <script type="text/javascript">
     $(document).ready(function(){
      $('.full-share').click(function(e){
        e.preventDefault();
        FB.ui(
        {
          method: 'feed',
          name: '<%= @show_video.title %>',
          link: 'http://imaginal.media/videos/<%= @show_video.id %>',
          picture: '<%= @show_video.facebook_thumbnail %>',
          description: '<%= @show_video.description %>',
          message: ''
        });
      });
    });
     </script>
   
     </div>
   </div>


   <div id="facebook-popup">
    <%= link_to image_tag("../assets/x-mark.jpg", :class => "close-popup") %>
    <div class="fb-like-box" data-href="https://www.facebook.com/imaginal.media" data-width="300" data-height="300" data-colorscheme="light" data-show-faces="true" data-header="true" data-stream="false" data-show-border="true"></div>
  </div>

  <div class="facebook-comments"></div>
      <script type="text/javascript">
        var width = $('.facebook-comments').width();
        $('.facebook-comments').html('<div class="fb-comments" data-href="http://imaginal.media/videos/<%= @show_video.id %>" data-width="' + width + '" data-numposts="5" data-colorscheme="dark"></div>');
      </script>


  <div class="carousel-footer">
      <%= render 'shared/carousel', title: "More Videos", subtitle: "", id: 1, videos: @small_vids, category: nil %>
  </div>


    <div id="alert"></div>


</div>