config/routes.rb
ImaginalUpgrade::Application.routes.draw do

  ActiveAdmin.routes(self)

  match 'users/sign_in' => 'pages#home', via: 'get'

  devise_for :users, :skip => [:registrations, :passwords], :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root :to => "pages#home"

  get 'profiles/:id/:name', :to => 'profiles#show'
  resources :profiles, only: [:show]

  get 'videos/:id/:name', :to => 'videos#show'
  put 'videos/:id/:name', :to => 'videos#update'
  post 'videos/:id', :to => 'videos#destroy'
  post 'videos/:id/:name', :to => 'videos#destroy'
  resources :videos

  resources :categories
  resources :tags

  match '/add_rating' => 'ratings#add_rating', via: 'post'

  match '/set_preference' => 'preferences#set_preference', via: 'post'

  get '/:id', to: 'pages#show'

end

app/views/shared/_bottom_nav.html.erb
<div class="footer">
    <!--<ul>
      <li><%= link_to "Privacy", "/privacy" %></li>
      <li><%= link_to "Terms", "/terms" %></li>
    </ul>-->
</div>

app/views/shared/_carousel.html.erb
<div class="row-fluid">
  <div class="carousel slide" id="carousel_<%=id %>">

    <% if !category.nil? %>
      <h2 tooltip="<%= category.description %>" class="tooltip<%=id+1 %>" id="category-<%=category.id.to_s %>" data-value="<%=title %>" data-id="category-<%=category.id.to_s %>" data-default="<%=category.name %>" data-alternates="<%=category.name %><% if category.alternates != '' %>, <%=category.alternates %><% end %>">
          <%=title %><span><%=subtitle %></span></h2><br>
    <% else %>
        <h2><%=title %><span><%=subtitle %></span></h2><br>
    <% end %>
    <div class="carousel-inner">

        <% per_page = 4 %>
        <% index = 0 %>
        <% total = 0 %>
        <% videos.each do |video| %>
          <% if index == 0 %>
            <% if total != 0 %>
              <%= '</ul></div>'.html_safe %>
            <% end %>
            <div class="item<% if total == 0 %> active<% end %>"><ul class="thumbnails">
          <% end %>

          <li class="span3">
            <div class="thumbnail">
              <%= link_to image_tag(video.thumbnail), video_path(video) %>
            </div>
            <div class="caption"><%= link_to (truncate(video.title, length: 50)), video_path(video) %></div>
          </li>

          <% index = index + 1 %>
          <% total = total + 1 %>

          <% if index == per_page %>
            <% index = 0 %>
          <% end %>
        <% end %>
        </ul></div>
    </div>

    <div class="carousel-mobile">
      <ul class="thumbnails">
        <% videos.each do |video| %>

          <li class="span3">
              <div class="thumbnail">
                  <%= link_to image_tag(video.thumbnail), video_path(video) %>
              </div>
              <div class="caption"><%= link_to (truncate(video.title, length: 50)), video_path(video) %></div>
          </li>
        <% end %>
      </ul>
    </div>

    <a data-slide="prev" href="#carousel_<%=id %>" class="left carousel-control"><img src="/assets/left-arrow.png"></a>
    <a data-slide="next" href="#carousel_<%=id %>" class="right carousel-control"><img src="/assets/right-arrow.png"></a>
  </div>
</div>

app/views/shared/_forms.html.erb
<!-- Modal -->
<div class="modal fade submit-vid-form" id="submit-vid-form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h1>SUBMIT A VIDEO</h1>
            </div>
            <div class="modal-body">
                <%= form_for @video do |f| %>
                    <h2>TITLE</h2>
                    <h5>Give the video a snazzy title that makes people curious, e.g. "How to Start a Movement in 3 Minutes"</h5>
                    <%= f.text_field :title, :size => "80x40", required: :true, :autofocus => true, remote: true %>
                    <h2>URL</h2><h5>(Vimeo or YouTube)</h5>
                    <%= f.text_field :url, :size => "80x40", placeholder: 'http://', required: :true %>
                    <h2>DESCRIPTION</h2>
                    <h5>Tell us how this video impacted you and why it matters.</h5>
                    <%= f.text_area :description, :size => "81x4", :rows => 3, required: :true %>

                    <div style="display: none;">
                      <h2>Share With Your Friends</h2>
                      <label><%= f.check_box :post_to_facebook, checked: '' %> Post this to my Facebook feed</label>
                    </div>

                    <br>

                    <div class="modal-footer">
                        <% if current_user %>
                            <%= f.submit "Done" %>
                        <% else %>
                            <%= f.submit "Sign in with Facebook" %>
                        <% end %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

<% if current_user %>

    <script type="text/javascript">
        $(document).ready(function(){
            $('.cat h5').css('cursor', 'pointer');
            $('.cat h5').click(function() {
                initCategoryPreferenceModal(this);
            });

            $('.carousel h2').css('cursor', 'pointer');
            $('.carousel h2').click(function() {
              initCategoryPreferenceModal(this);
            });
        });
    </script>

    <!-- Modal -->
    <div class="modal fade submit-vid-form" id="category-preference-form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h1>Rename this category</h1>
                    <p>You can choose to name this category something else.</p>
                </div>
                <div class="modal-body">
                    <form action="#" method="post" class="category-preference-form">

                        <h2>OPTIONS</h2>

                        <input type="hidden" id="category-preference-form-name" value="">

                        <select name="options" id="category-preference-form-value">
                            <option value="test">Test</option>
                        </select>

                        <div class="modal-footer">
                            <input name="commit" type="submit" value="Save">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <% if @show_video && (flash[:new] || params[:new]) && (@show_video.user_id == current_user.id || current_user.is_admin?) %>

        <script type="text/javascript">
            $(document).ready(function(){
                $('#tag-vid-form').modal('show');
            });
        </script>

        <!-- Modal -->
        <div class="modal fade submit-vid-form" id="tag-vid-form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h1>YOUR VIDEO HAS BEEN CREATED</h1>
                        <p>Please take a moment to add some tags to the video.</p>
                    </div>
                    <div class="modal-body">
                        <%= form_for :video, method: :put do |f| %>
                            <h2>TAGS</h2>
                            <h5>Tags separated by commas.</h5>
                            <%= f.text_field :tag_list, :value => @show_video.tag_list %>
                            <div class="modal-footer">
                                <%= f.submit "Add Tags" %>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>

    <% if @show_video && (@show_video.user_id == current_user.id || current_user.is_admin?) %>



        <!-- Modal -->
        <div class="modal fade submit-vid-form" id="delete-vid-form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h1>DELETE VIDEO</h1>
                    </div>
                    <div class="modal-body">
                        <%= form_for :video, method: :destroy do |f| %>
                            <h5>Are you sure you want to delete this video?</h5>
                            <div class="modal-footer">
                                <%= f.submit "Delete This Video" %>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>

        <!-- Modal -->
        <div class="modal fade submit-vid-form" id="edit-vid-form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h1>EDIT VIDEO</h1>
                    </div>
                    <div class="modal-body">
                        <%= form_for :video, method: :put do |f| %>

                            <h2>TITLE</h2>
                            <h5>Give the video a snazzy title that makes people curious, e.g. "How to Start a Movement in 3 Minutes"</h5>
                            <%= f.text_field :title, :size => "80x40", required: :true, :autofocus => true, remote: true, :value => @show_video.title %>
                            <h2>URL</h2><h5>(Vimeo or YouTube)</h5>
                            <%= f.text_field :url, :size => "80x40", placeholder: 'http://', required: :true, :value => @show_video.url %>
                            <h2>DESCRIPTION</h2>
                            <h5>Tell us how this video impacted you and why it matters.</h5>
                            <%= f.text_area :description, :size => "81x4", :rows => 3, required: :true, :value => @show_video.description %><br>
                            <h2>TAGS</h2>
                            <h5>Tags separated by commas.</h5>
                            <%= f.text_field :tag_list, :value => @show_video.tag_list %>
                            <div class="modal-footer">
                                <%= f.submit "Done" %>
                            </div>
                            <div>
                                <a href="#" class="delete-video">Delete This Video</a>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
<% end %>

app/views/shared/_player.html.erb
<div id="player"></div>

<script type="text/javascript">


  var source_width = '<%=video.video_width %>';
  var source_height = '<%=video.video_height %>';

  var ratio = source_width / source_height;

  var width = $('#player').parent().width();
  var height = Math.round(width / ratio);



  var height = 510;
  if (height > source_height) {
    //height = source_height;
  }


  var width = Math.round(height * ratio);


  function resize_player() {

    var max_width = $('#player').parent().width();



    var height = 510;
    if (height > source_height) {
    //  height = source_height;
    }


    var width = Math.round(height * ratio);

    if(width > max_width) {
      width = $('#player').parent().width();
      height = Math.round(width / ratio);
    }

    $('#player').width(width).height(height);


    //var width = $('#player').parent().width();
    //var height = Math.round(width / ratio);

    //$('#player').width(width).height(height);


    //var width = $('#player').parent().width();
    //var height = Math.round(width / ratio);

    //$('#player').width(width).height(height);

  }

  $(window).resize(function() {
   // resize_player();
  })


</script>

<% if video.provider == 'youtube' %>

  <script src="http://www.youtube.com/player_api"></script>
  <script type="text/javascript">
    // create youtube player
    var player;

    function onYouTubePlayerAPIReady() {
      player = new YT.Player('player', {
        height: height,
        width: width,
        playerVars: {
          controls: 0,
          showinfo: 0,
          iv_load_policy: 3
        },
        videoId: '<%=video.provider_id %>',
        events: {
          'onReady': onPlayerReady,
          'onStateChange': onPlayerStateChange
        }
      });
    }

    // autoplay video
    function onPlayerReady(event) {
      <% if autoplay %>
        event.target.playVideo();
      <% end %>
    }

    function playerStart() {
        //player.stopVideo();
        player.playVideo();
    }

    // when video ends
    function onPlayerStateChange(event) {
      if(event.data === 0) {
        if(typeof playerFinished == 'function') {
          playerFinished();
        }
      }
    }


    resize_player();

    $(window).resize(function() {
      resize_player();
    })


  </script>

<% elsif video.provider == 'vimeo' %>
  <script src="http://a.vimeocdn.com/js/froogaloop2.min.js"></script>
  <script type="text/javascript">
    var html = '<iframe id="player-iframe" src="//player.vimeo.com/video/<%=video.provider_id %>?api=1&player_id=player-iframe<% if autoplay %>&autoplay=true<% end %>&badge=0&byline=0&portrait=0&title=0" width="' + width + '" height="' + height + '" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>';
    $('#player').html(html);

    $(document).ready(function() {
      // Listen for the ready event for any vimeo video players on the page
      var player = $('#player-iframe')[0];
      $f(player).addEvent('ready', ready);

      function addEvent(element, eventName, callback) {
        if (element.addEventListener) {
          element.addEventListener(eventName, callback, false);
        }
        else {
          element.attachEvent(eventName, callback, false);
        }
      }

      function ready(player_id) {
        var froogaloop = $f(player_id);

        function onFinish() {
          froogaloop.addEvent('finish', function(data) {
            if(typeof playerFinished == 'function') {
              playerFinished();
            }
          });
        }
        onFinish();
      }
    });

    function playerStart() {
        var player = $('#player-iframe')[0];
        $f(player).api("seekTo", "0").api('play');
    }

  </script>

<%end%>

app/views/shared/_top_nav.html.erb
<!--<div class="navbar">
  <div class="inner-nav">
    <ul>
      <li class="nav-left logo"><%= link_to image_tag("logo.png"), root_path %></li>
      <% if user_signed_in? %>
        <li class="to-sub-vid-modal"><a href="#submit-video"></a></li>
        <% if current_user && current_user.is_admin? %>
                <li class="nav-right"><%= link_to "ADMIN", '/admin' %></li>
        <% end %>

        <li class="nav-right thumb"><a href="http://facebook.com/<%=current_user.uid %>"><img alt="Signed in as <%=current_user.name %>" title="Signed in as <%=current_user.name %>" src="https://graph.facebook.com/<%= current_user.uid %>/picture?type=square" /></a></li>
        <li class="nav-right"><%= link_to "SIGN OUT", destroy_user_session_path, :method => :delete %></li>
        <li class="nav-right"><%= link_to "MY VIDEOS", profile_path(current_user.profile) %></li>
        <li class="nav-right"><%= link_to "ALL VIDEOS", videos_path %></li>
      <% else %>
        <li class="to-sub-vid-modal"><a href="#submit-video"></a></li>
        <li class="nav-right"><%= link_to "SIGN IN WITH FACEBOOK", user_omniauth_authorize_path(:facebook) %></li>
        <li class="nav-right"><%= link_to "ALL VIDEOS", videos_path %></li>
      <% end %>
    </ul>
 </div>
</div>-->

<nav class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to image_tag("logo.png"), root_path, class: "navbar-brand" %>
        </div>
        <div id="navbar" class="collapse navbar-collapse pull-right">
            <ul class="nav navbar-nav">


                <li class="nav-right"><%= link_to "ALL VIDEOS", videos_path %></li>


                <% if user_signed_in? %>

                  <li class="nav-right"><%= link_to "MY VIDEOS", profile_path(current_user.profile) %></li>
                  <li class="nav-right"><%= link_to "SIGN OUT", destroy_user_session_path, :method => :delete %></li>
                  <li class="nav-right thumb"><a href="http://facebook.com/<%=current_user.uid %>"><img alt="Signed in as <%=current_user.name %>" title="Signed in as <%=current_user.name %>" src="https://graph.facebook.com/<%= current_user.uid %>/picture?type=square" /></a></li>

                  <% if current_user && current_user.is_admin? %>
                    <li class="nav-right"><%= link_to "ADMIN", '/admin' %></li>
                  <% end %>

                <% else %>

                  <li class="nav-right"><%= link_to "SIGN IN WITH FACEBOOK", user_omniauth_authorize_path(:facebook) %></li>

                <% end %>

                <li class="to-sub-vid-modal"><a href="#submit-video"></a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

app/views/shared/_videos.html.erb
<div class="add-vids-container">
  <% if @videos.count != 0  %>

    <ul>
      <% @videos.each do |video| %>
        <li>
          <div class="images">
            <%= link_to video_path(video) do %>
              <%=image_tag("/assets/empty.png", style: "background-image: url(" + video.thumbnail + ");") %>
              <span><%=truncate(video.title, length: 50) %></span>
            <% end %>
          </div>

          <div class="average-rating">
            <span>Imaginality: </span>
            <ul title="Imaginality rating: <%=video.average_rating %>">
              <% 1.upto(5) do |i| %>
                <% if i <= video.average_rating %>
                  <li class="star active"><%= image_tag("../assets/bigger-star-from-Jeff.png")%></li>
                <% else %>
                  <li class="star"><%= image_tag("../assets/bigger-star-from-Jeff.png")%></li>
                <% end %>
              <% end %>
            </ul>
          </div>
        </li>
      <% end %>
    </ul>

    <%= paginate @videos %>

  <% else %>
    <div class="none-found"><p>No videos found</p></div>
  <% end %>
</div>